name: Run anvil tests

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
      with:
        submodules: recursive

    - name: Run sudo apt update
      run: sudo apt update -y
    - name: Install astyle
      run: sudo apt install astyle -y

    - name: Run aclocal
      run: aclocal
    - name: Run autoconf
      run: autoconf
    - name: Run automake --add-missing
      run: automake --add-missing
    - name: Run ./configure
      run: ./configure
    - name: Run make
      run: make
    - name: Run make anviltest
      run: make anviltest
